---
## https://isc.sans.edu/forums/diary/Improving+Bash+Forensics+Capabilities/20887/
## https://blog.rootshell.be/2009/02/28/bash-history-to-syslog/
## Syslog option is a compile option in bash, mostly not enabled
## https://bugzilla.redhat.com/show_bug.cgi?id=1323808
## https://www.scip.ch/en/?labs.20150604 = auditd, rootsh, pam_tty_audit.so, sudo
## FIXME! activity from screen not logged (tmux OK), neither after sudo -s

## https://administratosphere.wordpress.com/2011/05/20/logging-every-shell-command/
## https://stackoverflow.com/questions/15753234/scoping-anomalies-with-typeset-r-and-readonly-keywords-in-ksh
- name: Enforce tighter bash settings
  blockinfile:
    dest: /etc/profile
    marker: "### {mark} ANSIBLE MANAGED BLOCK: bash settings ###"
    content: |
      export HISTCONTROL=
      export HISTFILE=$HOME/.bash_history
      export HISTFILESIZE={{ harden_bash_histfilesize | default(5000) }}
      export HISTIGNORE=
      export HISTSIZE={{ harden_bash_histsize | default(5000) }}
      export HISTTIMEFORMAT="{{ harden_bash_histtimeformat | default('%a %b %Y %T %z') }}"
      export PS1="{{ harden_bash_ps1 | default('[\A] \u@\h {\W}\\$ ') }}"
      if [ "X$SHELL" = '/bin/bash' ]; then
      typeset -r HISTCONTROL
      typeset -r HISTFILE
      typeset -r HISTFILESIZE
      typeset -r HISTIGNORE
      typeset -r HISTSIZE
      typeset -r HISTTIMEFORMAT
      fi
  tags: bash
## those two seems to create issues...
#      export PROMPT_COMMAND=\"history -a\"
#      typeset -r PROMPT_COMMAND

## Note: does not apply to ansible (direct call to python?) or root bash (why?)
## empty command are? typeset?
- name: Enable syslog logging of shell command through /etc/profile
  blockinfile:
    dest: /etc/profile
    marker: "### {mark} ANSIBLE MANAGED BLOCK: bash2syslog ###"
    content: |
      if [ "X$SHELL" = '/bin/bash' ]; then
      function log2syslog
      {
         declare command
         command=$(fc -ln -0)
         #[ "X$command" != "X" ] && logger -p local1.notice -t bash -i -- $USER : $command
         #[ "X$command" != "X" ] && logger -p local1.notice -t bash -i -- $USER : $command -- `env -0`
         [ "X$command" != "X" ] && logger -p local1.notice -t bash -i -- $USER : $command --- $PWD, $OLDPWD, $SSH_CLIENT
      }
      trap log2syslog DEBUG
      fi
  tags: bash

- stat: path=/etc/rsyslog.d
  register: rsyslog
- name: get rsyslog version
  command: "rsyslogd -v | awk -F'[ ,]' '/rsyslogd/ { print $2 }'"
  changed_when: false
  register: rsyslog_v
- name: add rsyslog configuration to filter to a specific file
  template: src=49-bash2syslog.conf.j2 dest=/etc/rsyslog.d/49-bash2syslog.conf mode=0644 backup=yes
  notify:
    - restart rsyslog
  when: rsyslog.stat.exists
  tags: bash

