---
## usual suspect: http://bastille-linux.sourceforge.net/, https://cisofy.com/lynis/, https://fedorahosted.org/aqueduct/wiki,
## https://github.com/fcaviggia/hardening-script-el6
## https://github.com/major/securekickstarts

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
- name: Include version-specific variables for Debian.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_distribution == 'Debian'
- name: Include version-specific variables for RedHat
  include_vars: "RedHat-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- name: Include version-specific variables for Alpine
  include_vars: "Alpine.yml"
  when: ansible_os_family == "Alpine"

- include: travis.yml
  when: ansible_os_family != "Windows"

- include: debian-apt-source.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

## FIXME! travis/docker/xenial+trusty: 'Error: No information about packages! (Maybe no deb entries?)\r\ndpkg: error processing package apt-show-versions (--configure)'
## https://groups.google.com/forum/#!topic/beagleboard/jXb9KhoMOsk  = Not that, settings non-existent
- name: Install some hardening packages
  package: name={{ item }} state=present update_cache=yes
  with_items: "{{ harden_pkg }}"
- name: Remove some packages
  package:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items: "{{ harden_pkg_remove }}"

- block:
    - name: Install arpwatch
      package: name=arpwatch state=present
    - name: Ensure arpwatch service is enabled and started
      service: name=arpwatch state=started enabled=yes
  when: harden_arpwatch and not (ansible_virtualization_type is defined and (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker"))
- name: Install arpwatch
  package:
    name: arpwatch
    state: absent
  when: not harden_arpwatch or (ansible_virtualization_type is defined and (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "docker"))

- include: linux.yml
  when: ansible_system == 'Linux'

- name: Debian | Harden
  include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Redhat | Harden
  include: redhat.yml
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Alpine | Harden
  include: alpine.yml
  when: ansible_os_family == "Alpine"

- include: unix.yml
  when: ansible_system == 'Linux' or ansible_distribution == 'OpenBSD'

- include: restrict_compiler.yml
  when: harden_restrict_compiler is defined and harden_restrict_compiler

- include: bash2syslog.yml
  when: harden_bash2syslog is defined and harden_bash2syslog

- include: root-forward.yml
  when: harden_rootforward is defined and harden_rootforward != ""

- include: fail2ban.yml

- include: vim-swapfiles.yml
- include: llmnr-systemd.yml

- include: testing.yml
  when: harden_testing
